
language: node_js
node_js: 10
script: yarn run lint
branches:
  only:
    - develop
    - master

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: dev
    on:
      branch: develop
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: latest
    on:
      tag: true

